### ISSUE TITLE
can you give a toggle button to make the panel show and display

### ISSUE THREAD

**Issue by akiritoa** [byteyilabs/yi-note#122] opened 2023-06-16 03:18 UTC
I want a toggle button to make the panel show and display, otherwise I should write by myself

**Comment by WeberAlex** [comment] 2023-08-09 14:56
And make the panel resizable so that I don't need to open a separate issue.

**Comment by WeberAlex** [comment] 2023-08-11 03:45
duplicate of #106

**Comment by shuowu** [comment] 2024-03-17 16:43
Panel toggle issue has been resolved and released in version 1.8.1 in [chrome web store](https://chromewebstore.google.com/detail/yinote/fhpgggnmdlmekfdpkdgeiccfkignhkdf)

**Closed by shuowu** 2024-03-17 16:43 UTC
